[features]
seeds = false
skip-lint = false

[programs.localnet]
token_extensions = "HYThq3CykDNuJzJVu2Xx7LVhQ2xTmAVhJgULmJwu9ZNu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/token-extensions",
] 